In [1]:
import numpy as np
import pandas as pd
from sklearn import feature_extraction,preprocessing,model_selection,linear_model

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
train.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [5]:
len(train)

7613

In [6]:
train = train.drop(["location",'keyword','id'],axis=1)

In [7]:
train.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 2 columns):
text      7613 non-null object
target    7613 non-null int64
dtypes: int64(1), object(1)
memory usage: 119.0+ KB


In [9]:
train

text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
5     #RockyFire Update => California Hwy. 20 closed...       1
6     #flood #disaster Heavy rain causes flash flood...       1
7     I'm on top of the hill and I can see a fire in...       1
8     There's an emergency evacuation happening now ...       1
9     I'm afraid that the tornado is coming to our a...       1
10          Three people died from the heat wave so far       1
11    Haha South Tampa is getting flooded hah- WAIT ...       1
12    #raining #flooding #Florida #TampaBay #Tampa 1...       1
13              #Flood in Bago Myanmar #We arrived Bago       1
14    Damage to school bus on 80 in multi car crash ...       1
15                                       What's up man?       0
16                                        I love fruits       0
17                                     Summer is lovely       0
18                                    My car is so fast       0
19                         What a goooooooaaaaaal!!!!!!       0
20                               this is ridiculous....       0
21                                    London is cool ;)       0
22                                          Love skiing       0
23                                What a wonderful day!       0
24                                             LOOOOOOL       0
25                       No way...I can't eat that shit       0
26                                Was in NYC last week!       0
27                                   Love my girlfriend       0
28                                            Cooool :)       0
29                                   Do you like pasta?       0
...                                                 ...     ...
7583  Pic of 16yr old PKK suicide bomber who detonat...       1
7584  These boxes are ready to explode! Exploding Ki...       0
7585  Calgary Police Flood Road Closures in Calgary....       1
7586  #Sismo DETECTADO #JapÌ_n 15:41:07 Seismic inte...       1
7587                                 Sirens everywhere!       0
7588  BREAKING: #ISIS claims responsibility for mosq...       1
7589                                     Omg earthquake       1
7590  SEVERE WEATHER BULLETIN No. 5 FOR: TYPHOON ‰ÛÏ...       1
7591  Heat wave warning aa? Ayyo dei. Just when I pl...       1
7592  An IS group suicide bomber detonated an explos...       1
7593  I just heard a really loud bang and everyone i...       0
7594  A gas thing just exploded and I heard screams ...       1
7595  NWS: Flash Flood Warning Continued for Shelby ...       1
7596  RT @LivingSafely: #NWS issues Severe #Thunders...       1
7597  #??? #?? #??? #??? MH370: Aircraft debris foun...       1
7598  Father-of-three Lost Control of Car After Over...       1
7599  1.3 #Earthquake in 9Km Ssw Of Anza California ...       1
7600  Evacuation order lifted for town of Roosevelt:...       1
7601  #breaking #LA Refugio oil spill may have been ...       1
7602  a siren just went off and it wasn't the Forney...       1
7603  Officials say a quarantine is in place at an A...       1
7604  #WorldNews Fallen powerlines on G:link tram: U...       1
7605  on the flip side I'm at Walmart and there is a...       1
7606  Suicide bomber kills 15 in Saudi security site...       1
7607  #stormchase Violent Record Breaking EF-5 El Re...       1
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [10]:
count_vectorizer = feature_extraction.text.CountVectorizer()

In [11]:
train_vectors = count_vectorizer.fit_transform(train['text'])

In [12]:
print(train_vectors.todense())
print(train_vectors.todense().shape)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(7613, 21637)


In [13]:
test_vectors = count_vectorizer.transform(test['text'])

In [14]:
clf = linear_model.RidgeClassifier()

In [15]:
scores = model_selection.cross_val_score(clf,train_vectors,train['target'],cv=3,scoring='f1')
scores

array([0.60355649, 0.57607656, 0.64485082])

In [16]:
clf.fit(train_vectors,train['target'])

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
        max_iter=None, normalize=False, random_state=None, solver='auto',
        tol=0.001)

In [17]:
sample_submission = pd.read_csv('sample_submission.csv')

In [18]:
sample_submission['target']=clf.predict(test_vectors)

In [19]:
sample_submission.head()

id  target
0   0       0
1   2       1
2   3       1
3   9       0
4  11       1

In [20]:
sample_submission.to_csv('submission_1.csv',index=False)

In [21]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [25]:
gnb.fit(train_vectors.toarray(),train['target'])

GaussianNB(priors=None)

In [26]:
sample_submission = pd.read_csv('sample_submission.csv')
sample_submission['target']=clf.predict(test_vectors.toarray())
sample_submission.head()

id  target
0   0       0
1   2       1
2   3       1
3   9       0
4  11       1

In [27]:
sample_submission.to_csv('submission_2.csv',index=False)

In [28]:
scores = model_selection.cross_val_score(gnb,train_vectors.toarray(),train['target'],cv=3,scoring='f1')
scores

array([0.59505988, 0.59182922, 0.63034188])